### ISSUE TITLE
Unanchored parts stack on top of each other

### ISSUE THREAD

**Issue by Crcoli7307** [iiPythonx/xenon#2] opened 2023-02-09 18:31 UTC
If you put unanchored parts in the Xenon folder, then launch the game with Xenon enabled, the unanchored parts will lag out and stack on top of each other.

**Comment by iiPythonx** [comment] 2023-02-09 23:53
Internal engine bug caused by Xenon overduplicating unanchored parts.
Looking into it.

**Comment by iiPythonx** [comment] 2023-02-09 23:59
Fixed as of 315579a

**Closed as completed by iiPythonx** 2023-02-09 23:59 UTC
